spring:
  application:
    name: study-hexagonal
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inventory;MODE=MYSQL;INIT=RUNSCRIPT FROM 'src/main/resources/inventory.sql';
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console